-- Show the data 
SELECT * FROM customer;


--Q1- what is the total revenue generated by male vs female cystomer ?

SELECT gender , ROUND(SUM(purchase_amount),2) AS total_amount
FROM customer 
GROUP BY gender 


--Q2- which customers used a discount but still spent more than the average purchase amount ?

SELECT customer_id 
FROM customer 
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer )


--Q3- which are the top 5 products with the highest average review rating ?

SELECT item_purchased , ROUND(AVG(review_rating)::numeric,2) AS Average_Rating
FROM customer 
GROUP BY item_purchased
ORDER BY Average_Rating DESC
LIMIT 5;


--Q4- compare the average Purchase amounts between standard and Express shipping ?

SELECT shipping_type ,ROUND(AVG(purchase_amount)::numeric,2) AS avg_shipping_type
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type


--Q5- do subscibed customers spend more ? Compare average spend and total revenue between subscribers and non_subscribers ?

SELECT subscription_status , ROUND(AVG(purchase_amount)::numeric,2) AS average_amount , sum(purchase_amount) as Total_revenue
from customer 
GROUP BY subscription_status

--Q6- which 5 products have the highest percentage of purchases with discount applied ?
SELECT 
    item_purchased,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5 ;

--Q7- Segment customuers into New , Recruting , and Loyal based on their total number of previous purchases, and show th count of each segment ?
WITH segment_type AS (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS total_customers
FROM segment_type
GROUP BY customer_segment;


--Q8-what are the top 3 most purchased products within each category ?

WITH item_counts AS (
SELECT category , item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category , item_purchased 
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


--Q9- are customers who are repeat buyers (more than 5 previous_purchases) are likely to subscribe ?

SELECT subscription_status , COUNT(customer_id) AS repeat_buyers
FROM customer 
WHERE previous_purchases >= 5 
GROUP BY subscription_status


--Q10- what is the revenue contribution of each age group ?

SELECT age_group , SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group 
ORDER BY total_revenue DESC
